#!/usr/bin/env node
// Generates contract-dom.json: what the published hmi/ + viewer/ modules need
// from their embedder, beyond the ES imports they carry themselves.
//
//   node tools/gen_dom_contract.mjs [outfile]     (default: contract-dom.json)
//
// Why this exists (finding ARQ-3): the `release` branch ships the module tree
// and `contract.json`, but the modules weld themselves to a DOM they do not
// publish — 200-odd element ids that only exist in the dev-host's urdf.html —
// and take their host/scene edges through an untyped `deps` object of up to 30
// callbacks. Every lookup is guarded with `if (el)`, so an embedder that
// provides none of it gets a tree that loads cleanly and does nothing, in
// silence. This manifest is the missing half of the contract.
//
// It is a STATIC SCAN, not a type system: it reports the literal ids and dep
// keys the source mentions. Computed ids (`getElementById(varName)`) cannot be
// seen and are reported as a count so the number is never mistaken for
// completeness.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const SCAN_ROOTS = ["hmi", "viewer"];

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (name.endsWith(".js")) out.push(full);
  }
  return out;
}

// `initXxx(nextDeps)` / `createXxx(deps)` / `createXxx({ a, b })` — the entry
// points the embedder calls. The destructured form names its deps inline.
const ENTRY_RE = /export\s+function\s+((?:init|create)[A-Za-z0-9_]*)\s*\(([^)]*)\)/g;
const DOM_ID_RE = /getElementById\(\s*["'`]([^"'`]+)["'`]\s*\)/g;
const DOM_DYNAMIC_RE = /getElementById\(\s*(?!["'`])/g;
const DEP_READ_RE = /\b(?:deps|nextDeps|options)\.([A-Za-z_$][\w$]*)/g;
// `const { a, b } = deps;` — how the factory modules unpack theirs.
const DEP_DESTRUCTURE_RE = /(?:const|let|var)\s*\{([^}]*)\}\s*=\s*(?:deps|nextDeps|options)\b/g;

// Names out of a destructuring pattern body, ignoring renames/defaults/comments.
function destructuredKeys(body) {
  return body
    .replace(/\/\/[^\n]*/g, "")
    .split(",")
    .map((part) => part.split(/[:=]/)[0].trim())
    .filter((key) => /^[A-Za-z_$][\w$]*$/.test(key));
}

const modules = {};
const allIds = new Set();

for (const root of SCAN_ROOTS) {
  for (const file of walk(join(REPO_ROOT, root))) {
    const rel = relative(REPO_ROOT, file).split(sep).join("/");
    const src = readFileSync(file, "utf8");

    const domIds = [...src.matchAll(DOM_ID_RE)].map((m) => m[1]);
    const dynamicLookups = [...src.matchAll(DOM_DYNAMIC_RE)].length;
    const deps = new Set([...src.matchAll(DEP_READ_RE)].map((m) => m[1]));
    for (const match of src.matchAll(DEP_DESTRUCTURE_RE)) {
      destructuredKeys(match[1]).forEach((key) => deps.add(key));
    }

    const entries = [];
    for (const match of src.matchAll(ENTRY_RE)) {
      entries.push(match[1]);
      // Destructured signature: `createCalendarUi({ escapeHtml, onOpen })`.
      const params = match[2];
      if (params.includes("{")) {
        const inner = params.slice(params.indexOf("{") + 1, params.lastIndexOf("}"));
        destructuredKeys(inner).forEach((key) => deps.add(key));
      }
    }

    if (!domIds.length && !deps.size && !entries.length) continue;
    domIds.forEach((id) => allIds.add(id));
    modules[rel] = {
      entryPoints: entries.sort(),
      requiredDomIds: [...new Set(domIds)].sort(),
      injectedDeps: [...deps].sort(),
      ...(dynamicLookups ? { computedDomLookups: dynamicLookups } : {}),
    };
  }
}

const out = {
  $comment:
    "Companion to contract.json for embedders of the published hmi/ + viewer/ tree. "
    + "requiredDomIds are element ids the module looks up by literal string; every lookup "
    + "is guarded, so a missing element is a SILENT no-op, not an error. injectedDeps are "
    + "the keys each initXxx/createXxx entry point reads off its dependency object. "
    + "Generated by tools/gen_dom_contract.mjs — a static scan, do not hand-edit.",
  contractVersion: 2,
  totals: {
    modules: Object.keys(modules).length,
    domIds: allIds.size,
  },
  domIds: [...allIds].sort(),
  modules: Object.fromEntries(Object.entries(modules).sort(([a], [b]) => a.localeCompare(b))),
};

const outfile = resolve(REPO_ROOT, process.argv[2] || "contract-dom.json");
writeFileSync(outfile, JSON.stringify(out, null, 2) + "\n", "utf8");
console.log(
  `contract-dom: ${out.totals.modules} modules, ${out.totals.domIds} DOM ids -> `
  + relative(REPO_ROOT, outfile).split(sep).join("/"),
);
