#!/usr/bin/env node
// Build the publishable shell: the page the published hmi/ + viewer/ modules
// expect to find themselves in.
//
//   node tools/gen_shell.mjs --out <dir> [--in <urdf.html>]
//
// Why this exists
// ---------------
// contract-dom.json tells an embedder WHICH element ids the modules look up.
// It cannot tell them the structure: several modules reach inside an element
// (`card.querySelector(".spool-select-icon")`), and the class names the modules
// toggle (`slicer-fullscreen`, `status-not-enough`, `files-collapsed-for-print`)
// mean nothing without the stylesheet. And every getElementById in this code
// base is guarded, so an embedder that gets one id wrong is not told: the
// feature simply does nothing, forever. That is the exact failure mode that hid
// 36 dead lookups in this repository for months, and shipping the ids as a list
// exports it to the consumer.
//
// So the release artefact carries a page that is correct by construction,
// derived from the one the app actually runs, plus the stylesheet, the vendored
// three and the icons it references.
//
// What it deliberately does NOT carry: the assembly. Wiring the 25 modules
// together lives in urdf_viewer.js, which owns the Three.js scene and is not
// published. The shell leaves a marked, empty entry point for the embedder's
// own module — an honest hole rather than a page that looks complete and is
// inert.
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const STATIC = join(REPO_ROOT, "apps", "dev-host", "src", "avisualizer", "web", "static");

function option(flag, fallback) {
  const at = process.argv.indexOf(flag);
  return at !== -1 && process.argv[at + 1] ? process.argv[at + 1] : fallback;
}

// `--in` exists so the refuse-on-unknown-markup path can be exercised for real
// rather than asserted against this file's own source text.
const SRC_HTML = resolve(option("--in", join(STATIC, "urdf.html")));
const OUT = resolve(option("--out", join(REPO_ROOT, "shell")));

// Absolute dev-host URLs -> paths relative to the shell. The published modules
// keep their own relative imports, so only the page's own references move.
const REWRITES = [
  [/\/static\/vendor\//g, "./vendor/"],
  [/\/static\/icons\//g, "./icons/"],
  [/\/static\/urdf_viewer\.css(\?v=\d+)?/g, "./urdf_viewer.css"],
  [/\/hmi\//g, "./hmi/"],
  [/\/viewer\//g, "./viewer/"],
];

const ENTRY_PLACEHOLDER = `  <!-- ===================================================================
       APP ENTRY — intentionally empty.

       This shell is the DOM and the styling. The wiring that instantiates the
       published modules is NOT published: it lives in the dev host's
       urdf_viewer.js, which owns the Three.js scene.

       Replace the script below with your own module. It should import from
       ./hmi/ and ./viewer/ and call each domain's createXxx/initXxx entry
       point with the deps listed in contract-dom.json.

       Nothing here throws if you do not: every getElementById is guarded, so
       an unwired shell renders and sits there. That silence is the reason
       contract-dom.json exists — read it before assuming a feature is broken.
       =================================================================== -->
  <script type="module" data-app-entry>
    // Your assembly goes here.
  </script>`;

let html = readFileSync(SRC_HTML, "utf8");

// Drop the dev host's own entry script; the embedder supplies the assembly.
const entryPattern = /\s*<!-- App entry\.[\s\S]*?-->\s*<script type="module" data-app-entry[^>]*><\/script>/;
if (!entryPattern.test(html)) {
  console.error("shell: could not find the app-entry script in urdf.html.");
  console.error("If the entry markup changed, update tools/gen_shell.mjs to match —");
  console.error("silently shipping the dev host's entry would 404 for every consumer.");
  process.exit(1);
}
html = html.replace(entryPattern, `\n${ENTRY_PLACEHOLDER}`);

for (const [pattern, replacement] of REWRITES) {
  html = html.replace(pattern, replacement);
}

// Cache-busting query strings are the dev host's problem; the consumer versions
// the whole artefact by submodule commit.
html = html.replace(/(\.(?:js|css|png|woff2))\?v=\d+/g, "$1");

html = html.replace(
  "<title>URDF Viewer</title>",
  "<title>Meltio HMI</title>\n  <!-- Generated by tools/gen_shell.mjs from urdf.html — do not edit. -->",
);

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "index.html"), html);
cpSync(join(STATIC, "urdf_viewer.css"), join(OUT, "urdf_viewer.css"));
cpSync(join(STATIC, "vendor"), join(OUT, "vendor"), { recursive: true });
cpSync(join(STATIC, "icons"), join(OUT, "icons"), { recursive: true });

const ids = (html.match(/id="([^"]+)"/g) || []).length;
console.log(`shell: ${ids} element ids, css + vendor + icons -> ${OUT}`);
